"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const book_controller_1 = require("./book.controller");
const router = (0, express_1.Router)();
router.post('/', book_controller_1.createBook);
router.get('/', book_controller_1.getAllBooks);
router.get('/:id', book_controller_1.getSingleBook);
router.put('/:id', book_controller_1.updateBook);
router.delete('/:id', book_controller_1.deleteBook);
exports.default = router;
